onlinecart/config/routes.rb
Rails.application.routes.draw do
  resources :products

  root 'products#index'

resources :orders do
  member do
    get 'add_to_cart'
  end
end

end

onlinecart/app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :product
end

onlinecart/app/models/product.rb
class Product < ActiveRecord::Base
  has_many :orders
end

onlinecart/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

onlinecart/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def add_to_cart
    @x = Product.find(params[:id])
    @order = Order.new
  end

  def new

  end

  def create
    puts("#{order_params}")
    order = Order.new(order_params)
    redirect_to orders_path if order.save
  end

  def index
    @orders = Order.all
  end

  private

  def order_params
    params.require(:order).permit(:name, :price, :quantity, :description, :product_id)
  end

end

onlinecart/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end


  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :description, :quantity)
  end
end

onlinecart/app/helpers/application_helper.rb
module ApplicationHelper
end

onlinecart/app/helpers/orders_helper.rb
module OrdersHelper
end

onlinecart/app/helpers/products_helper.rb
module ProductsHelper
end

onlinecart/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Onlinecart</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

onlinecart/app/views/orders/add_to_cart.html.erb
<h1>Your Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @x.name %></td>
        <td><%= @x.price %></td>
        <td><%= form_for @order do |f| %>

         <%= f.hidden_field :product_id, :value => @x.id %>
        <%= f.number_field :quantity %>
        <%= f.submit 'Buy Now' %>
        <% end %>
        </td>
      </tr>
  </tbody>
</table>

<%= link_to 'Orders', orders_path %>

onlinecart/app/views/orders/index.html.erb
<h1>All Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |x| %>
      <tr>
        <td><%= x.product.name %></td>
        <td><%= x.quantity %></td>
      </tr>
    <% end %>
  </tbody>
</table>

onlinecart/app/views/products/_form.html.erb
<h1>New Product</h1>
<%= form_for(@product) do |f| %>

  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<p>
  <%= f.label :name %>
  <%= f.text_area :name %>

<p>
  <%= f.label :price %>
  <%= f.number_field :price %>
</p>

<p>
  <%= f.label :quantity %>
  <%= f.number_field :quantity %>
</p>

</p>
  <%= f.label :description %>
  <%= f.text_area :description %>
<p>
  <%= f.submit %>
</p>

<% end %>

<%= link_to 'Home', products_path %>

onlinecart/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

onlinecart/app/views/products/index.html.erb
<h1>All Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= product.description %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add Product', new_product_path %>

onlinecart/app/views/products/new.html.erb
<%= render 'form' %>

onlinecart/app/views/products/show.html.erb
<p>
  <strong>Name: </strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price: </strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity: </strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Description: </strong>
  <%= @product.description %>
</p>

<%= link_to 'Home', products_path %>
<%= link_to 'Add to cart', add_to_cart_order_path(@product.id)%>