app/config/routes.rb
Rails.application.routes.draw do
  resources :appdata

end

app/app/models/appdatum.rb
class Appdatum < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 4}
  validates :description, presence: true, length: { minimum: 4}
  validates :phone_number, presence: true, format: {with:/[0-9]+/, message: "only allows numbers"}, length: { minimum: 10}
  validates :address, presence: true, length: { minimum: 4}

  before_validation :foo

  protected

  def foo
    unless name.nil?
      self.name = name.capitalize unless name.blank?
    end
  end
end

app/app/controllers/appdata_controller.rb
class AppdataController < ApplicationController
  before_action :set_appdatum, only: [:show, :edit, :update, :destroy]

  # GET /appdata
  # GET /appdata.json
  def index
    @appdata = Appdatum.all
  end

  # GET /appdata/1
  # GET /appdata/1.json
  def show
    @appdatum=Appdatum.find(params[:id])
  end

  def abc
  end
  # GET /appdata/new
  def new
    @appdatum = Appdatum.new
  end

  # GET /appdata/1/edit
  def edit
    @appdatum=Appdatum.find(params[:id])
  end

  # POST /appdata
  # POST /appdata.json
  def create
    @appdatum = Appdatum.new(appdatum_params)

    respond_to do |format|
      if @appdatum.save
        format.html { redirect_to @appdatum, notice: 'Appdatum was successfully created.' }
        format.json { render :show, status: :created, location: @appdatum }
      else
        format.html { render :new }
        format.json { render json: @appdatum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appdata/1
  # PATCH/PUT /appdata/1.json
  def update
    respond_to do |format|
      if @appdatum.update(appdatum_params)
        format.html { redirect_to @appdatum, notice: 'Appdatum was successfully updated.' }
        format.json { render :show, status: :ok, location: @appdatum }
      else
        format.html { render :edit }
        format.json { render json: @appdatum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appdata/1
  # DELETE /appdata/1.json
  def destroy
    @appdatum.destroy
    respond_to do |format|
      format.html { redirect_to appdata_url, notice: 'Appdatum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appdatum
      @appdatum = Appdatum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appdatum_params
      params.fetch(:appdatum).permit(:name, :description, :phone_number, :address, )
    end
end

app/app/helpers/appdata_helper.rb
module AppdataHelper
end

app/app/views/appdata/_form.html.erb
<%= form_for(@appdatum) do |f| %>
  <% if @appdatum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appdatum.errors.count, "error") %> prohibited this appdatum from being saved:</h2>

      <ul>
      <% @appdatum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
  <%= f.label :name %>
  <%= f.text_area :name %>
  </p>
  <p>
  <%= f.label :description %>
  <%= f.text_area :description %>
  </p>
    <p>
  <%= f.label :phone_number %>
  <%= f.text_area :phone_number %>
  </p>
 <p>
  <%= f.label :address %>
  <%= f.text_area :address %>
  </p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/app/views/appdata/abc.html.erb
<h1>Hello</h1>

app/app/views/appdata/edit.html.erb
<h1>Editing Appdatum</h1>

<%= render 'form' %>

<%= link_to 'Show', @appdatum %> |
<%= link_to 'Back', appdata_path %>

app/app/views/appdata/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Appdata</h1>

<table>
  <thead>
    <tr>
      <th>app name</th>
      <th>app description</th>
      <th>phone number</th>
      <th>address</th>
      <th colspan="3"></th>

    </tr>
  </thead>

  <tbody>
    <% @appdata.each do |appdatum| %>
      <tr>
        <td><%= appdatum.name %></td>
        <td><%= appdatum.description %></td>
        <td><%= appdatum.phone_number %></td>
        <td><%= appdatum.address %></td>
        <td><%= link_to 'Show', appdatum %></td>
        <td><%= link_to 'Edit', edit_appdatum_path(appdatum) %></td>
        <td><%= link_to 'Destroy', appdatum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appdatum', new_appdatum_path %>

app/app/views/appdata/new.html.erb
<h1>New Appdatum</h1>

<%= render 'form' %>

<%= link_to 'Back', appdata_path %>

app/app/views/appdata/show.html.erb
<p id="notice"><%= notice %></p>
  <strong>Name:</strong>
  <%= @appdatum.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @appdatum.description %>
</p>

<p>
  <strong>phone number:</strong>
  <%= @appdatum.phone_number %>
</p>
<p>
  <strong>Address:</strong>
  <%= @appdatum.address %>
</p>


<%= link_to 'Edit', edit_appdatum_path(@appdatum) %> |
<%= link_to 'Abc', abc_appdata_path %> |
<%= link_to 'Back', appdata_path %>

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>